import "dotenv/config";
import { PrismaClient, PriceMode } from "@prisma/client";

const prisma = new PrismaClient();

const categories = [
  {
    name: "MS Pipes",
    slug: "ms-pipes",
    code: "CAT-01",
    description: "Mild steel pipes for industrial, construction and plumbing applications.",
    sortOrder: 1,
  },
  {
    name: "Stainless Steel",
    slug: "stainless-steel",
    code: "CAT-02",
    description: "Premium stainless steel pipes and fittings.",
    sortOrder: 2,
  },
  {
    name: "Elbows & Tees",
    slug: "elbows-tees",
    code: "CAT-03",
    description: "Industrial elbows, tees and pipe fittings.",
    sortOrder: 3,
  },
  {
    name: "Flanges",
    slug: "flanges",
    code: "CAT-04",
    description: "Industrial pipe flanges for reliable connections.",
    sortOrder: 4,
  },
  {
    name: "Water Pumps",
    slug: "water-pumps",
    code: "CAT-05",
    description: "Reliable water pumps for domestic and industrial applications.",
    sortOrder: 5,
  },
  {
    name: "Plumbing Items",
    slug: "plumbing-items",
    code: "CAT-06",
    description: "Quality plumbing components and accessories.",
    sortOrder: 6,
  },
  {
    name: "Safety Wear",
    slug: "safety-wear",
    code: "CAT-07",
    description: "Industrial safety clothing and protective equipment.",
    sortOrder: 7,
  },
  {
    name: "Safety Boots",
    slug: "safety-boots",
    code: "CAT-08",
    description: "Protective industrial safety footwear.",
    sortOrder: 8,
  },
  {
    name: "Electrical Components",
    slug: "electrical-components",
    code: "CAT-09",
    description: "Circuit breakers, contactors and motor starters for industrial electrical systems.",
    sortOrder: 9,
  },
  {
    name: "Water Heaters",
    slug: "water-heaters",
    code: "CAT-10",
    description: "Electric water heaters for residential and commercial use.",
    sortOrder: 10,
  },
  {
    name: "Structural Steel",
    slug: "structural-steel",
    code: "CAT-11",
    description: "I-beams and structural steel sections for construction.",
    sortOrder: 11,
  },
  {
    name: "Valves",
    slug: "valves",
    code: "CAT-12",
    description: "Industrial valves for flow control in piping systems.",
    sortOrder: 12,
  },
  {
    name: "Steel Plates",
    slug: "steel-plates",
    code: "CAT-13",
    description: "Mild steel plates and sheets for fabrication and construction.",
    sortOrder: 13,
  },
  {
    name: "Bath & Sanitary Fittings",
    slug: "bath-sanitary-fittings",
    code: "CAT-14",
    description: "Taps, faucets, sinks, shower heads and bathroom accessories.",
    sortOrder: 14,
  },
];

// Every image path here is a real photo extracted from the client's own
// product flyer, bundled at build time in the frontend's
// public/images/products/ folder. These are relative paths (not absolute
// URLs) — the browser resolves them against whichever origin is serving
// the frontend, so this works in dev and in production without editing
// this file again, and without depending on the backend's own domain.
const products = [
  {
    name: "Mild Steel Pipe 2 Inch",
    slug: "mild-steel-pipe-2-inch",
    sku: "BOL-MS-002",
    categorySlug: "ms-pipes",
    description: "High-quality mild steel pipe suitable for plumbing, fabrication and industrial applications.",
    material: "Mild Steel",
    size: '2"',
    brand: "Bolatemi",
    price: 28500,
    stockQuantity: 150,
    image: "/images/products/black_pipe.png",
    specifications: {
      size: "2 inch",
      material: "Mild Steel",
      standard: "Industrial Grade",
      application: "Plumbing / Construction",
    },
    featured: true,
  },
  {
    name: "Galvanised Steel Pipe",
    slug: "galvanised-steel-pipe",
    sku: "BOL-MS-GLV-001",
    categorySlug: "ms-pipes",
    description: "Hot-dip galvanised steel pipe, rust-resistant, suitable for outdoor and water-supply installations.",
    material: "Galvanised Steel",
    size: 'Multiple sizes',
    brand: "Bolatemi",
    price: 32000,
    stockQuantity: 110,
    image: "/images/products/galvanised_pipe.png",
    specifications: {
      material: "Galvanised Steel",
      coating: "Hot-Dip Galvanised",
      application: "Outdoor / Water Supply",
    },
    featured: false,
  },
  {
    name: "Stainless Steel Pipe",
    slug: "stainless-steel-pipe",
    sku: "BOL-SS-001",
    categorySlug: "stainless-steel",
    description: "Premium stainless steel pipe designed for corrosion resistance and long-term industrial use.",
    material: "Stainless Steel",
    size: '2"',
    brand: "Bolatemi",
    price: 65000,
    stockQuantity: 80,
    image: "/images/products/stainless_pipe.png",
    specifications: {
      material: "Stainless Steel",
      finish: "Polished",
      application: "Industrial / Plumbing",
      corrosionResistance: "High",
    },
    featured: true,
  },
  {
    name: "Steel Elbow 90 Degree",
    slug: "steel-elbow-90-degree",
    sku: "BOL-ELB-090",
    categorySlug: "elbows-tees",
    description: "Heavy-duty 90-degree steel elbow for industrial piping systems.",
    material: "Carbon Steel",
    size: '2"',
    brand: "Bolatemi",
    price: 8500,
    stockQuantity: 200,
    image: "/images/products/elbow.png",
    specifications: {
      angle: "90 Degree",
      material: "Carbon Steel",
      size: "2 inch",
      application: "Industrial Piping",
    },
    featured: false,
  },
  {
    name: "Steel Tee Fitting",
    slug: "steel-tee-fitting",
    sku: "BOL-TEE-001",
    categorySlug: "elbows-tees",
    description: "Standard-specification tee fitting for branching pipe runs in plumbing and industrial installations.",
    material: "Carbon Steel",
    size: 'Multiple sizes',
    brand: "Bolatemi",
    price: 9500,
    stockQuantity: 180,
    image: "/images/products/tee.png",
    specifications: {
      type: "Tee Fitting",
      material: "Carbon Steel",
      application: "Industrial Piping",
    },
    featured: false,
  },
  {
    name: "Industrial Steel Flange",
    slug: "industrial-steel-flange",
    sku: "BOL-FLG-001",
    categorySlug: "flanges",
    description: "Heavy-duty industrial flange for secure pipe connections and pressure systems.",
    material: "Carbon Steel",
    size: '4"',
    brand: "Bolatemi",
    price: 18500,
    stockQuantity: 120,
    image: "/images/products/flange.png",
    specifications: {
      type: "Industrial Flange",
      material: "Carbon Steel",
      size: "4 inch",
      application: "Pipe Connection",
    },
    featured: true,
  },
  {
    name: "Industrial Water Pump",
    slug: "industrial-water-pump",
    sku: "BOL-PMP-001",
    categorySlug: "water-pumps",
    description: "Reliable high-performance surface water pump suitable for commercial and industrial applications.",
    material: "Cast Iron",
    brand: "Bolatemi",
    price: 185000,
    stockQuantity: 25,
    image: "/images/products/surface_pump.png",
    specifications: {
      type: "Centrifugal Pump",
      application: "Industrial / Commercial",
      power: "2HP",
      voltage: "220V",
    },
    featured: true,
  },
  {
    name: "Submersible Water Pump",
    slug: "submersible-water-pump",
    sku: "BOL-PMP-SUB-001",
    categorySlug: "water-pumps",
    description: "Submersible pump for boreholes and deep-well water supply, with power cable included.",
    material: "Stainless Steel",
    brand: "Bolatemi",
    price: 95000,
    stockQuantity: 18,
    image: "/images/products/submersible_pump.png",
    specifications: {
      type: "Submersible Pump",
      application: "Borehole / Deep Well",
      voltage: "220V",
    },
    featured: false,
  },
  {
    name: "Premium Plumbing Fittings Set",
    slug: "premium-plumbing-fittings-set",
    sku: "BOL-PLB-001",
    categorySlug: "plumbing-items",
    description: "Professional plumbing fittings suitable for installation, maintenance and repair work.",
    material: "PVC / Brass",
    brand: "Bolatemi",
    price: 32000,
    stockQuantity: 100,
    image: "/images/products/plumbing_material.png",
    specifications: {
      type: "Plumbing Fittings",
      material: "PVC / Brass",
      application: "Residential / Commercial",
    },
    featured: false,
  },
  {
    name: "Assorted Bolts and Nuts",
    slug: "assorted-bolts-and-nuts",
    sku: "BOL-FST-001",
    categorySlug: "plumbing-items",
    description: "Assorted galvanised bolts and nuts in standard sizes for flange, fitting and general fastening use.",
    material: "Galvanised Steel",
    size: "Assorted",
    brand: "Bolatemi",
    price: 3500,
    stockQuantity: 300,
    image: "/images/products/bolt_and_nuts.png",
    specifications: {
      type: "Fasteners",
      material: "Galvanised Steel",
      application: "Flange / General Fastening",
    },
    featured: false,
  },
  {
    name: "High Visibility Safety Jacket",
    slug: "high-visibility-safety-jacket",
    sku: "BOL-SFT-001",
    categorySlug: "safety-wear",
    description: "High-visibility reflective safety jacket for construction and industrial environments.",
    material: "Polyester",
    size: "XL",
    brand: "Bolatemi",
    price: 18000,
    stockQuantity: 75,
    image: "/images/products/safety_jacket.png",
    specifications: {
      type: "Reflective Safety Jacket",
      material: "Polyester",
      size: "XL",
      application: "Construction / Industrial",
    },
    featured: true,
  },
  {
    name: "Industrial Safety Boots",
    slug: "industrial-safety-boots",
    sku: "BOL-BOT-001",
    categorySlug: "safety-boots",
    description: "Durable industrial safety boots with reinforced protection for demanding work environments.",
    material: "Leather / Rubber",
    size: "42",
    brand: "Bolatemi",
    price: 35000,
    stockQuantity: 60,
    image: "/images/products/safety_boot.png",
    specifications: {
      type: "Safety Boot",
      material: "Leather / Rubber",
      size: "42",
      protection: "Reinforced Toe",
      application: "Industrial / Construction",
    },
    featured: true,
  },

  // ---- More Safety Wear / Boots ----
  {
    name: "SWAG FIT Safety Boot",
    slug: "swagfit-safety-boot",
    sku: "BOL-BOT-002",
    categorySlug: "safety-boots",
    description: "Swag Fit black leather safety boot with steel toe protection, reflective panel and lace-up design.",
    material: "Leather",
    size: "43",
    brand: "Swag Fit",
    price: 28000,
    stockQuantity: 40,
    image: "/images/products/swagfit_safety_boot.jpg",
    specifications: { type: "Safety Boot", material: "Leather", size: "43", brand: "Swag Fit" },
    featured: false,
  },
  {
    name: "KAKA Safety Boot (Yellow)",
    slug: "kaka-safety-boot-yellow",
    sku: "BOL-BOT-003",
    categorySlug: "safety-boots",
    description: "KAKA Safety heavy-duty yellow PVC safety boot with steel toe cap, CE and EN ISO 20345 certified.",
    material: "PVC / Rubber",
    size: "43",
    brand: "KAKA Safety",
    price: 22000,
    stockQuantity: 50,
    image: "/images/products/kaka_safety_boot.jpg",
    specifications: { type: "Safety Boot", material: "PVC / Rubber", size: "43", brand: "KAKA Safety", certification: "CE, EN ISO 20345" },
    featured: false,
  },
  {
    name: "Industrial Safety Helmet",
    slug: "industrial-safety-helmet",
    sku: "BOL-HLM-001",
    categorySlug: "safety-wear",
    description: "ABS safety helmet with adjustable harness, available in blue, white, green and yellow.",
    material: "ABS Plastic",
    brand: "Bolatemi PPE",
    price: 4500,
    stockQuantity: 200,
    image: "/images/products/safety_helmets_set.jpg",
    specifications: { type: "Safety Helmet", material: "ABS", colors: "Blue, White, Green, Yellow", adjustable: "Yes" },
    featured: false,
  },

  // ---- Electrical Components ----
  {
    name: "Schneider Electric TeSys Contactor LC1D40A",
    slug: "schneider-tesys-contactor-lc1d40a",
    sku: "BOL-ELEC-001",
    categorySlug: "electrical-components",
    description: "Genuine Schneider Electric TeSys D-series contactor, model LC1D40A, for motor control and industrial switching applications.",
    material: "Thermoplastic / Copper",
    brand: "Schneider Electric",
    price: 45000,
    stockQuantity: 30,
    image: "/images/products/schneider_contactor_1.jpg",
    images: ["/images/products/schneider_contactor_1.jpg", "/images/products/schneider_contactor_2.jpg"],
    specifications: { model: "LC1D40A", brand: "Schneider Electric", series: "TeSys D", application: "Motor Control / Switching" },
    featured: true,
  },
  {
    name: "CHMT DC Circuit Breaker DZ47-125DC",
    slug: "chmt-dc-circuit-breaker",
    sku: "BOL-ELEC-002",
    categorySlug: "electrical-components",
    description: "CHMT DC-rated circuit breaker, model DZ47-125DC D125, rated 1000V DC, suitable for solar and DC power systems.",
    material: "Thermoplastic",
    brand: "CHMT",
    price: 28000,
    stockQuantity: 40,
    image: "/images/products/chmt_dc_breaker.jpg",
    specifications: { model: "DZ47-125DC D125", brand: "CHMT", rating: "1000V DC, Icu=10kA", application: "Solar / DC Power Systems" },
    featured: false,
  },
  {
    name: "Schneider Electric MCCB EZC250F 160A",
    slug: "schneider-mccb-ezc250f",
    sku: "BOL-ELEC-003",
    categorySlug: "electrical-components",
    description: "Schneider Electric moulded case circuit breaker (MCCB), model EZC250F, 160A rating, for industrial distribution panels.",
    material: "Thermoplastic",
    brand: "Schneider Electric",
    price: 95000,
    stockQuantity: 15,
    image: "/images/products/schneider_mccb.jpg",
    specifications: { model: "EZC250F", brand: "Schneider Electric", rating: "160A", application: "Distribution Panel" },
    featured: true,
  },
  {
    name: "Schneider Electric TeSys Motor Starter GV2ME20",
    slug: "schneider-tesys-gv2me20",
    sku: "BOL-ELEC-004",
    categorySlug: "electrical-components",
    description: "Schneider Electric TeSys motor circuit breaker / starter, model GV2ME20, adjustable 13-18A, with Start/Stop control.",
    material: "Thermoplastic",
    brand: "Schneider Electric",
    price: 38000,
    stockQuantity: 25,
    image: "/images/products/schneider_gv2me20.jpg",
    specifications: { model: "GV2ME20", brand: "Schneider Electric", range: "13-18A", series: "TeSys" },
    featured: false,
  },
  {
    name: "Schneider Electric MCB iC60N 32A",
    slug: "schneider-mcb-ic60n-32a",
    sku: "BOL-ELEC-005",
    categorySlug: "electrical-components",
    description: "Schneider Electric miniature circuit breaker (MCB), iC60N series, 2-pole, 32A, type C curve.",
    material: "Thermoplastic",
    brand: "Schneider Electric",
    price: 12500,
    stockQuantity: 80,
    image: "/images/products/schneider_ic60n_mcb.jpg",
    specifications: { model: "iC60N", brand: "Schneider Electric", rating: "C 32A", poles: "2-Pole" },
    featured: false,
  },

  // ---- Water Heaters ----
  {
    name: "AquaPlex Electric Water Heater",
    slug: "aquaplex-electric-water-heater",
    sku: "BOL-WH-001",
    categorySlug: "water-heaters",
    description: "AquaPlex electric storage water heater with digital display, available in multiple tank capacities for home and commercial use.",
    material: "Stainless Steel Tank",
    brand: "AquaPlex",
    price: 55000,
    stockQuantity: 20,
    image: "/images/products/water_heaters.jpg",
    specifications: { type: "Storage Water Heater", brand: "AquaPlex", power: "Electric", sizes: "Multiple capacities available" },
    featured: true,
  },

  // ---- Structural Steel ----
  {
    name: "Structural Steel I-Beam",
    slug: "structural-steel-i-beam",
    sku: "BOL-STR-001",
    categorySlug: "structural-steel",
    description: "Hot-rolled structural steel I-beam for construction framing and heavy structural applications. Priced per length/specification.",
    material: "Structural Steel",
    brand: "Bolatemi",
    price: 0,
    priceMode: "REQUEST_QUOTE",
    stockQuantity: 0,
    image: "/images/products/steel_ibeam_1.jpg",
    images: ["/images/products/steel_ibeam_1.jpg", "/images/products/steel_ibeam_2.jpg"],
    specifications: { type: "I-Beam", material: "Structural Steel", application: "Construction Framing" },
    featured: true,
  },

  // ---- Valves ----
  {
    name: "Knife Gate Valve",
    slug: "knife-gate-valve",
    sku: "BOL-VLV-001",
    categorySlug: "valves",
    description: "Industrial knife gate valve with handwheel actuator, for flow control in slurry, wastewater and bulk material handling systems.",
    material: "Cast Iron / Stainless Steel",
    brand: "Bolatemi",
    price: 0,
    priceMode: "REQUEST_QUOTE",
    stockQuantity: 0,
    image: "/images/products/knife_gate_valves.jpg",
    specifications: { type: "Knife Gate Valve", actuator: "Handwheel", application: "Slurry / Wastewater / Bulk Handling" },
    featured: false,
  },

  // ---- Steel Plates ----
  {
    name: "Mild Steel Plate 4x8x50mm",
    slug: "mild-steel-plate-4x8x50mm",
    sku: "BOL-PLT-001",
    categorySlug: "steel-plates",
    description: "Mild steel plate, 4x8 feet sheet size, 50mm thickness, for heavy fabrication and structural work.",
    material: "Mild Steel",
    size: "4 x 8 x 50mm",
    brand: "Bolatemi",
    price: 0,
    priceMode: "REQUEST_QUOTE",
    stockQuantity: 0,
    image: "/images/products/steel_plates_4x8x50.jpg",
    specifications: { type: "Steel Plate", size: "4x8x50mm", material: "Mild Steel", application: "Heavy Fabrication" },
    featured: false,
  },

  // ---- More MS Pipes ----
  {
    name: "MS Pipe - Bulk Stock",
    slug: "ms-pipe-bulk-stock",
    sku: "BOL-MS-BULK-001",
    categorySlug: "ms-pipes",
    description: "Mild steel pipe available in bulk quantities for large construction and industrial projects. Size and grade to specification.",
    material: "Mild Steel",
    brand: "Bolatemi",
    price: 0,
    priceMode: "REQUEST_QUOTE",
    stockQuantity: 0,
    image: "/images/products/ms_pipe_bulk_stack.jpg",
    specifications: { type: "MS Pipe", material: "Mild Steel", supply: "Bulk / Wholesale" },
    featured: false,
  },
  {
    name: "MS Pipe with End Caps (Export Grade)",
    slug: "ms-pipe-end-caps-export-grade",
    sku: "BOL-MS-BULK-002",
    categorySlug: "ms-pipes",
    description: "Export-grade mild steel pipe with protective end caps, ready for bulk shipment and large-scale supply.",
    material: "Mild Steel",
    brand: "Bolatemi",
    price: 0,
    priceMode: "REQUEST_QUOTE",
    stockQuantity: 0,
    image: "/images/products/ms_pipe_end_caps.jpg",
    specifications: { type: "MS Pipe", material: "Mild Steel", grade: "Export Grade", packaging: "End-Capped" },
    featured: false,
  },

  // ---- More Stainless Steel ----
  {
    name: "Stainless Steel Pipe - Bulk Stock",
    slug: "stainless-steel-pipe-bulk-stock",
    sku: "BOL-SS-BULK-001",
    categorySlug: "stainless-steel",
    description: "Stainless steel pipe available in bulk quantities, corrosion-resistant, for industrial and food-grade applications.",
    material: "Stainless Steel",
    brand: "Bolatemi",
    price: 0,
    priceMode: "REQUEST_QUOTE",
    stockQuantity: 0,
    image: "/images/products/stainless_pipe_bulk_stack.jpg",
    specifications: { type: "Stainless Steel Pipe", material: "Stainless Steel", supply: "Bulk / Wholesale" },
    featured: false,
  },

  // ---- More Elbows & Tees ----
  {
    name: "Stainless Steel Tee Fittings",
    slug: "stainless-steel-tee-fittings",
    sku: "BOL-FIT-TEE-002",
    categorySlug: "elbows-tees",
    description: "Butt-weld stainless steel tee fittings for branching pipe runs in industrial and sanitary piping systems.",
    material: "Stainless Steel",
    brand: "Bolatemi",
    price: 0,
    priceMode: "REQUEST_QUOTE",
    stockQuantity: 0,
    image: "/images/products/stainless_tee_fittings.jpg",
    specifications: { type: "Tee Fitting", material: "Stainless Steel", connection: "Butt-Weld" },
    featured: false,
  },

  // ---- More Flanges ----
  {
    name: "Forged Steel Flange (Zinc-Plated)",
    slug: "forged-steel-flange-zinc-plated",
    sku: "BOL-FLG-002",
    categorySlug: "flanges",
    description: "Forged carbon steel flange with yellow zinc-plated finish, drilled bolt pattern, for pipe and vessel connections.",
    material: "Carbon Steel (Zinc-Plated)",
    brand: "Bolatemi",
    price: 0,
    priceMode: "REQUEST_QUOTE",
    stockQuantity: 0,
    image: "/images/products/brass_flanges_box.jpg",
    specifications: { type: "Forged Flange", finish: "Zinc-Plated", material: "Carbon Steel" },
    featured: false,
  },

  // ---- More Plumbing Items ----
  {
    name: "AcquaFlex Wall-Hung WC & Basin Set",
    slug: "acquaflex-wc-basin-set",
    sku: "BOL-PLB-002",
    categorySlug: "plumbing-items",
    description: "AcquaFlex England wall-hung water closet and pedestal basin set, ceramic finish, for modern bathroom installations.",
    material: "Vitreous China",
    brand: "AcquaFlex England",
    price: 145000,
    stockQuantity: 12,
    image: "/images/products/acquaflex_wc_basin.jpg",
    specifications: { type: "WC & Basin Set", brand: "AcquaFlex England", material: "Vitreous China", mount: "Wall-Hung" },
    featured: true,
  },
  {
    name: "BRIMIX PTFE Thread Seal Tape",
    slug: "brimix-ptfe-thread-seal-tape",
    sku: "BOL-PLB-003",
    categorySlug: "plumbing-items",
    description: "BRIMIX professional-grade PTFE thread seal tape, Italy standard, 100% hermetic seal for pipe joints.",
    material: "PTFE",
    brand: "BRIMIX",
    price: 500,
    stockQuantity: 500,
    image: "/images/products/brimix_ptfe_tape.jpg",
    specifications: { type: "Thread Seal Tape", brand: "BRIMIX", standard: "Italy Standard", seal: "100% Hermetic" },
    featured: false,
  },

  // ---- More Water Pumps ----
  {
    name: "QIFENG Submersible Sewage Pump 4-inch",
    slug: "qifeng-submersible-sewage-pump",
    sku: "BOL-PMP-002",
    categorySlug: "water-pumps",
    description: "Heavy-duty QIFENG submersible sewage pump, 4-inch (DN100) discharge, for wastewater and drainage applications.",
    material: "Cast Iron",
    brand: "QIFENG",
    price: 320000,
    stockQuantity: 6,
    image: "/images/products/qifeng_submersible_pump.jpg",
    specifications: { type: "Submersible Sewage Pump", brand: "QIFENG", discharge: "DN100 / 4 inch", application: "Wastewater / Drainage" },
    featured: true,
  },
  {
    name: "CNP Stainless Multistage Water Pump",
    slug: "cnp-stainless-multistage-pump",
    sku: "BOL-PMP-003",
    categorySlug: "water-pumps",
    description: "CNP horizontal multistage centrifugal pump with stainless steel casing, for booster and pressure systems.",
    material: "Stainless Steel",
    brand: "CNP",
    price: 145000,
    stockQuantity: 10,
    image: "/images/products/cnp_multistage_pump.jpg",
    specifications: { type: "Multistage Centrifugal Pump", brand: "CNP", casing: "Stainless Steel" },
    featured: false,
  },
  {
    name: "CAPENDA Diesel Water Pump",
    slug: "capenda-diesel-water-pump",
    sku: "BOL-PMP-004",
    categorySlug: "water-pumps",
    description: "CAPENDA diesel-engine-driven water pump on a portable frame, for irrigation and construction site dewatering.",
    material: "Cast Iron / Steel Frame",
    brand: "CAPENDA",
    price: 285000,
    stockQuantity: 8,
    image: "/images/products/capenda_diesel_pump.jpg",
    specifications: { type: "Diesel Water Pump", brand: "CAPENDA", frame: "Portable" },
    featured: true,
  },
  {
    name: "DAB Water Pump",
    slug: "dab-water-pump",
    sku: "BOL-PMP-005",
    categorySlug: "water-pumps",
    description: "DAB (Italy) electric water pump, model K30/100M, 1.5HP, for domestic and light commercial water supply.",
    material: "Cast Iron",
    brand: "DAB",
    price: 98000,
    stockQuantity: 14,
    image: "/images/products/dab_water_pump.jpg",
    specifications: { type: "Electric Water Pump", brand: "DAB", model: "K30/100M", power: "1.5HP" },
    featured: false,
  },
  {
    name: "Vertical Inline Centrifugal Pump",
    slug: "vertical-inline-centrifugal-pump",
    sku: "BOL-PMP-006",
    categorySlug: "water-pumps",
    description: "Vertical inline centrifugal pump for circulation and pressure-boosting applications in commercial buildings.",
    material: "Cast Iron",
    brand: "Bolatemi",
    price: 265000,
    stockQuantity: 5,
    image: "/images/products/vertical_inline_pump.jpg",
    specifications: { type: "Vertical Inline Pump", application: "Circulation / Pressure Boosting" },
    featured: false,
  },

  // ---- Bath & Sanitary Fittings ----
  {
    name: "Brushed Steel Basin Mixer Tap",
    slug: "brushed-steel-basin-mixer-tap",
    sku: "BOL-BATH-001",
    categorySlug: "bath-sanitary-fittings",
    description: "Single-handle brushed stainless steel basin mixer tap for bathroom sinks, modern curved design.",
    material: "Stainless Steel",
    brand: "Bolatemi",
    price: 18500,
    stockQuantity: 35,
    image: "/images/products/brushed_basin_mixer_tap.jpg",
    specifications: { type: "Basin Mixer Tap", finish: "Brushed Steel", handle: "Single-Handle" },
    featured: false,
  },
  {
    name: "Gold Pull-Out Kitchen Faucet",
    slug: "gold-pullout-kitchen-faucet",
    sku: "BOL-BATH-002",
    categorySlug: "bath-sanitary-fittings",
    description: "Gold-finish pull-out kitchen faucet with flexible spring hose, boxed and complete with fittings.",
    material: "Brass (Gold Finish)",
    brand: "Bolatemi",
    price: 32000,
    stockQuantity: 20,
    image: "/images/products/gold_pullout_kitchen_faucet.jpg",
    specifications: { type: "Kitchen Faucet", finish: "Gold", feature: "Pull-Out Spring Hose" },
    featured: true,
  },
  {
    name: "Round Shower Head (Assorted Colors)",
    slug: "round-shower-head-assorted",
    sku: "BOL-BATH-003",
    categorySlug: "bath-sanitary-fittings",
    description: "Round rainfall shower head, available in white, blue, dark blue and pink finishes.",
    material: "ABS Plastic",
    brand: "Bolatemi",
    price: 8500,
    stockQuantity: 60,
    image: "/images/products/shower_heads_set.jpg",
    specifications: { type: "Shower Head", colors: "White, Blue, Dark Blue, Pink", style: "Rainfall" },
    featured: false,
  },
  {
    name: "UniHome Bidet Shattaf Sprayer Set",
    slug: "unihome-bidet-shattaf-set",
    sku: "BOL-BATH-004",
    categorySlug: "bath-sanitary-fittings",
    description: "UniHome bidet spray set with flexible hose and wall bracket, complete toilet hygiene accessory kit.",
    material: "Chrome-Plated Brass",
    brand: "UniHome",
    price: 9500,
    stockQuantity: 45,
    image: "/images/products/unihome_shattaf_set.jpg",
    specifications: { type: "Bidet Sprayer Set", brand: "UniHome", finish: "Chrome-Plated" },
    featured: false,
  },
  {
    name: "VMAC Double Bowl Stainless Sink",
    slug: "vmac-double-bowl-sink",
    sku: "BOL-BATH-005",
    categorySlug: "bath-sanitary-fittings",
    description: "VMAC England premium double bowl single tray stainless steel kitchen sink, anti-rust, high-end handmade finish. 2ft & 3ft available.",
    material: "Stainless Steel",
    brand: "VMAC England",
    price: 65000,
    stockQuantity: 15,
    image: "/images/products/vmac_double_bowl_sink.jpg",
    specifications: { type: "Kitchen Sink", brand: "VMAC England", bowls: "Double Bowl, Single Tray", sizes: "2ft & 3ft available" },
    featured: true,
  },
  {
    name: "Stainless Steel Kitchen Mixer Tap",
    slug: "stainless-kitchen-mixer-tap",
    sku: "BOL-BATH-006",
    categorySlug: "bath-sanitary-fittings",
    description: "Curved-spout stainless steel kitchen mixer tap with swivel action, single-lever control.",
    material: "Stainless Steel",
    brand: "Bolatemi",
    price: 21000,
    stockQuantity: 28,
    image: "/images/products/stainless_kitchen_taps.jpg",
    specifications: { type: "Kitchen Mixer Tap", material: "Stainless Steel", feature: "Swivel Spout" },
    featured: false,
  },
  {
    name: "MMAAT Shattaf Sprayer Set (Assorted)",
    slug: "mmaat-shattaf-set-assorted",
    sku: "BOL-BATH-007",
    categorySlug: "bath-sanitary-fittings",
    description: "MMAAT bidet shattaf sprayer set with kink-free hose, available in blue, teal, white and orange.",
    material: "ABS / Braided Hose",
    brand: "MMAAT",
    price: 7500,
    stockQuantity: 55,
    image: "/images/products/mmaat_shattaf_set.jpg",
    specifications: { type: "Bidet Sprayer Set", brand: "MMAAT", colors: "Blue, Teal, White, Orange" },
    featured: false,
  },
  {
    name: "Brass Bib Tap (Wall-Mount)",
    slug: "brass-bib-tap-wall-mount",
    sku: "BOL-BATH-008",
    categorySlug: "bath-sanitary-fittings",
    description: "Solid brass wall-mount bib tap with cross handle, polished finish, for outdoor and utility water points.",
    material: "Solid Brass",
    brand: "Bolatemi",
    price: 14500,
    stockQuantity: 40,
    image: "/images/products/brass_bib_taps.jpg",
    specifications: { type: "Bib Tap", material: "Solid Brass", mount: "Wall-Mount", handle: "Cross Handle" },
    featured: false,
  },
  {
    name: "Kitchen Sink with Pull-Down Faucet Set",
    slug: "kitchen-sink-pulldown-faucet-set",
    sku: "BOL-BATH-009",
    categorySlug: "bath-sanitary-fittings",
    description: "Complete stainless steel kitchen sink with matching black pull-down spring faucet, drying rack and accessories included.",
    material: "Stainless Steel",
    brand: "Bolatemi",
    price: 78000,
    stockQuantity: 10,
    image: "/images/products/black_kitchen_sink_faucet.jpg",
    specifications: { type: "Kitchen Sink Set", material: "Stainless Steel", faucet: "Black Pull-Down Spring", includes: "Drying Rack" },
    featured: true,
  },
];

async function main() {
  console.log("Starting Bolatemi catalog seed...");

  const categoryMap = new Map<string, string>();

  for (const category of categories) {
    const saved = await prisma.category.upsert({
      where: { slug: category.slug },
      update: {
        name: category.name,
        code: category.code,
        description: category.description,
        sortOrder: category.sortOrder,
        isActive: true,
      },
      create: {
        name: category.name,
        slug: category.slug,
        code: category.code,
        description: category.description,
        sortOrder: category.sortOrder,
        isActive: true,
      },
    });

    categoryMap.set(category.slug, saved.id);
  }

  console.log(`Created/updated ${categoryMap.size} categories.`);

  // Each product is upserted independently inside its own try/catch — a
  // single bad record (bad category slug, a constraint violation, etc.)
  // must not silently take the other 11 down with it. The previous version
  // of this script let one failure throw all the way out of main(),
  // aborting the whole seed — including every product after the failing
  // one — with nothing but "Seeded 0 products" left to explain why.
  let successCount = 0;
  const failures: { name: string; error: string }[] = [];

  for (const product of products) {
    try {
      const categoryId = categoryMap.get(product.categorySlug);
      if (!categoryId) {
        throw new Error(`Category not found: ${product.categorySlug}`);
      }

      const savedProduct = await prisma.product.upsert({
        where: { sku: product.sku },
        update: {
          name: product.name,
          slug: product.slug,
          description: product.description,
          categoryId,
          material: product.material,
          brand: product.brand,
          size: product.size,
          specifications: product.specifications,
          priceMode: "priceMode" in product && product.priceMode === "REQUEST_QUOTE" ? PriceMode.REQUEST_QUOTE : PriceMode.FIXED,
          price: "priceMode" in product && product.priceMode === "REQUEST_QUOTE" ? null : product.price,
          currency: "NGN",
          stockQuantity: product.stockQuantity,
          isAvailable: true,
          isFeatured: product.featured,
        },
        create: {
          name: product.name,
          slug: product.slug,
          sku: product.sku,
          description: product.description,
          categoryId,
          material: product.material,
          brand: product.brand,
          size: product.size,
          specifications: product.specifications,
          priceMode: "priceMode" in product && product.priceMode === "REQUEST_QUOTE" ? PriceMode.REQUEST_QUOTE : PriceMode.FIXED,
          price: "priceMode" in product && product.priceMode === "REQUEST_QUOTE" ? undefined : product.price,
          currency: "NGN",
          stockQuantity: product.stockQuantity,
          isAvailable: true,
          isFeatured: product.featured,
        },
      });

      await prisma.productImage.deleteMany({ where: { productId: savedProduct.id } });
      const imageUrls = "images" in product && product.images ? product.images : [product.image];
      await prisma.productImage.createMany({
        data: imageUrls.map((url: string, i: number) => ({
          productId: savedProduct.id,
          url,
          altText: product.name,
          sortOrder: i,
        })),
      });

      console.log(`✓ ${product.name}`);
      successCount++;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.error(`✗ Failed to seed "${product.name}" (SKU ${product.sku}): ${message}`);
      failures.push({ name: product.name, error: message });
    }
  }

  console.log("");
  console.log(`Seeded ${successCount}/${products.length} products.`);
  if (failures.length > 0) {
    console.log("\nFailed products — fix these and re-run `npm run seed`:");
    failures.forEach((f) => console.log(`  - ${f.name}: ${f.error}`));
  } else {
    console.log("Bolatemi catalog seed completed successfully.");
  }

  const superAdminEmail = "admin@bolatemiglobal.com";
  const existingAdmin = await prisma.adminUser.findUnique({ where: { email: superAdminEmail } });
  if (!existingAdmin) {
    const bcrypt = await import("bcryptjs");
    const passwordHash = await bcrypt.hash("ChangeMe123!", 12);
    await prisma.adminUser.create({
      data: { name: "Super Admin", email: superAdminEmail, passwordHash, role: "SUPER_ADMIN" },
    });
    console.log(`\nCreated super admin: ${superAdminEmail} / ChangeMe123!  <-- change this password immediately`);
  }
}

main()
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
